/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Unlocked omega (v1.0)": "解锁欧米伽 (v1.0)",
    "DISCORD HERE": "加入DISCORD",
    "GUIDE HERE": "指南",
    "Incremental": "增量",
    "Note: Buyables MAY have a 1.5 sec delay due to performance issues.": "注意：由于性能问题，可购买 可能会有 1.5 秒的延迟。",
    "Keep Playing": "继续游戏",
    "leaves per second.": "叶子 每秒。",
    "Leaves to beat a tree": "叶子 去 击败一棵树",
    "points per second.": "点数 每秒。",
    "Start Playing": "开始游戏",
    "Start producing leaves.": "开始产生树叶。",
    "Trees": "树",
    "trees.": "树。",
    "Upgrades": "升级",
    "(Always buying max just deal with it it's easier like that.)": "（总是购买 最大 只是处理它，这样更容易。）",
    "Buyables": "可购买",
    "Don't Stop Playing": "不要停止游戏",
    "Point Multiplier": "点数乘数",
    "Leaf Multiplier": "叶子乘数",
    "Never End Your Playing": "永远不要结束你的游戏",
    "Softcap Extender": "软上限扩展器",
    "Holdup another layer?": "撑起另一层？",
    "How Are We Back In This Section?": "我们是如何回到这个部分的？",
    "HOW DOES THIS FEATURE WORK??": "这个功能是如何工作的？？",
    "I'M BROKEN :(": "我崩溃了 :(",
    "I'M EVEN MORE BROKEN": "我更崩溃了",
    "1 1/2 Infinities!": "1 1/2 无穷大！",
    "1 Point for each realm": "每个领域 1 点",
    "A Heaping Teaspoon of Replicanti Died for this.": "一茶匙的复制人为此而死。",
    "A Lot Of Replicanti Died For This.": "许多复制人为此而死。",
    "A Whole Lotta Points": "整点积分",
    "Absorb the power of the void.": "吸收虚空之力。",
    "Almost as Cool as Zuckerberg": "几乎和扎克伯格一样酷",
    "Another One": "另一个",
    "Antimatter Dimensions PTSD": "反物质维度 PTSD",
    "Antimatter Dimensions Reference": "反物质维度参考",
    "Ayo the Naming?": "Ayo 命名？",
    "Beat the advanced challenge.": "战胜高级挑战。",
    "Beat the easy challenge.": "战胜简单的挑战。",
    "Beat the hard challenge.": "战胜艰难的挑战。",
    "Blessed Up": "有福了",
    "Booster Bandit": "助推器强盗",
    "Break Infinity.": "打破无限。",
    "Buy the first 4 crypto upgrades.": "购买前 4 个加密升级。",
    "Cooler than Zuckerberg": "比扎克伯格还酷",
    "Degree In Computer Science": "计算机科学学位",
    "Demonic Infinity": "恶魔无限",
    "Demonic Infinity Power": "恶魔无限力量",
    "DILATION FROM ANTIMATTER DIMENSIONS????": "反物质维度的膨胀？？？？",
    "Dimensional Multi Millionaire": "次元百万富翁",
    "Do a singularity reset.": "进行奇点重置。",
    "Don't forget...": "别忘了...",
    "Easiest AD Challenge, but Harder?": "最简单的 AD 挑战，但更难？",
    "ee6": "ee6",
    "Even In The Void Eternity Is Gone.": "即使在虚无中，永恒也已逝去。",
    "Extend mod softcap to 50.": "将 mod softcap 扩展到 50。",
    "Extend tree softcap to 20.": "将树软顶扩展到 20。",
    "Get 1 code experience.": "获得 1 次代码体验。",
    "Get 1 infinity point.": "获得1个无限点。",
    "Get 1 jacorbian energy.": "获得 1 个雅可比能量。",
    "Get 1 point per second.": "每秒获得 1 点。",
    "Get 1 prestige power.": "获得 1 点声望力量。",
    "Get 1 Tree.": "获得 1 棵树。",
    "Get 1 void singularity.": "获得 1 个虚无奇点。",
    "Get 1.33e154 points and 1 infinity.": "获得 1.33e154 点和 1 个无穷大。",
    "Get 1.79e308 infinity points while absorbing void.": "吸收虚空获得1.79e308无限点数。",
    "Get 1000 willpower.": "获得1000意志力。",
    "Get 1024 bytes.": "得到 1024 字节。",
    "Get 115.74 points per second.": "每秒获得 115.74 点。",
    "Get 150 leaves": "获得150片叶子",
    "Get 1e100 code experience.": "获得 1e100 代码体验。",
    "Get 1e456 jacorbian energy.": "获得 1e456 雅可比能量。",
    "Get 1e6 willpower.": "获得1e6意志力。",
    "Get 250 leaf multipliers.": "获得 250 个叶倍增器。",
    "Get 4000 void singularities.": "获得4000个虚无奇点。",
    "Get 50 mods for each realm.": "每个领域获得 50 个模组。",
    "Get 500 of each energy type.": "获得每种能量类型 500。",
    "Get 60 trees.": "得到60棵树。",
    "INFINITE REPLICANTI?": "无限复制人？",
    "Infinitely More Realms": "无限更多的境界",
    "Infinitillionaire": "亿万富翁",
    "Infinity Dimensions After Replicanti?": "复制品 之后的无限维度？",
    "Inflated Singularity": "膨胀的奇点",
    "Jacorb Running Through Your Veins!": "Jacorb在你的血管中奔跑！",
    "Just Like Elon": "就像Elon",
    "Kilobyte": "千字节",
    "Make 4 mods.": "制作 4 个模组。",
    "Man of Many Realms": "多界之人",
    "More Mods Than Ducdat": "比 Ducdat 更多的模组",
    "Multiplyer Man": "乘法人",
    "MY BELOVED ETERNITY, WHERE IS IT????": "我心爱的永恒，它在哪里？？？？",
    "No Buyables?": "没有可购买？",
    "Not a Hevipelle Reference": "不是 Hevipelle 参考资料",
    "Not Even Close to Despacit": "甚至没有接近绝望",
    "Note: Some achievements are worth more than others": "注意：有些成就比其他成就更有价值",
    "Oh God Not Another Challenge.": "哦上帝不是另一个挑战。",
    "Photosynthesis Lover": "光合作用爱好者",
    "Pi Devourer": "Pi 吞噬者",
    "Pi Eater": "Pi 食客",
    "Pi Extremist": "Pi 极端分子",
    "Pi Fangirl": "Pi 迷妹",
    "Pi Muncher": "Pi 咀嚼者",
    "Pi on Drugs.": "Pi 上的药物。",
    "Reached ee2 Points!": "达到了ee2点！",
    "Seriously, where is eternity?": "说真的，永恒在哪里？",
    "Shrineful": "神圣",
    "Shrinetastic": "神庙",
    "Shrinetatious": "供奉",
    "Singularitree": "奇点树",
    "Softcap beginner": "软帽初学者",
    "Softcap Trainee": "软顶实习生",
    "Still Single Even In The Void?": "即使在虚空中仍然单身？",
    "Still Single???": "还是单身？？？",
    "The Big Hundred": "大百",
    "The Incremental God Tree\n\t\t\t\t\t\t\tDiscord": "增量神树\n\t\t\t\t\t\t\tDiscord",
    "THE INFLATION IS COMING.": "通胀即将来临。",
    "The Meta-Achievement": "元成就",
    "The Year This Mod Was Made?": "这个 Mod 是哪一年制作的？",
    "Theory Master": "理论大师",
    "True Virginity.": "真正的童贞。",
    "Unlock crypto dimensions.": "解锁加密维度。",
    "Unlock the hub.": "解锁集线器。",
    "Very first tree": "第一棵树",
    "Very powerful indeed.": "确实非常强大。",
    "Welcome to the Crypto Club": "欢迎来到加密俱乐部",
    "Where is my precious eternity?": "我宝贵的永恒在哪里？",
    "WHERE'S MY 1E800 POINTS?": "我的 1E800 积分在哪里？",
    "Where's My Inflation?": "我的通货膨胀在哪里？",
    "Why Can't I Have Reality As Well?": "为什么我也不能拥有现实？",
    "Willionaire": "亿万富翁",
    "Yay! I got my 1e800 Points!": "耶！ 我得到了我的 1e800 点！",
    "You are a Modder Now": "你现在是模组制作者",
    "Currently:": "当前：",
    "Double Trees": "双倍树",
    "Pointy Leaves": "尖叶",
    "Requirement Shortener": "需求缩短器",
    "Self explanatory.": "自我解释。",
    "Boosts point generation based on how much leaves you have for trees.": "根据你有多少树叶来增加点数生成。",
    "Unlock Something": "解锁一些东西",
    "Computer": "计算机",
    "crypto.": "加密。",
    "Main": "主界面",
    "on reset. (Based on points)": "在重置时。（基于点数）",
    "Reset for crypto": "重置以获得加密",
    "Boosts leaf generation based on crypto.": "基于加密提升叶子生成。",
    "Boosts point generation based on crypto.": "基于加密提升点数生成。",
    "Boosts tree generation based on crypto.": "基于加密提升树生成。",
    "Engineering": "工程",
    "Softcap starts later based on crypto.": "软上限 稍后基于 加密 启动。",
    "Inflated Game": "膨胀游戏",
    "Mega Tree Booster": "终级树助推器",
    "Unlocks crypto dimensions.": "解锁加密维度。",
    "x boost to point and leaf gain.": "x 提升点数和叶子增益。",
    "Crypto Dimensions": "加密维度",
    "Autobuys tree buyables and unlocks byte buyables": "自动购买树 可购买 并解锁字节 可购买",
    "Keep upgrades on crypto reset": "在加密重置时保留升级",
    "Metaverse": "元宇宙",
    "Supremely Inflated": "膨胀到极点",
    "Blockchain Technology": "区块链技术",
    "Crypto Multiplier": "加密乘数",
    "Crypto Dimension Multiplier": "加密维度乘数",
    "Point, Leaf and Tree Multiplier": "点数、叶子和树乘数",
    "Extremely Inflated": "极度膨胀",
    "boost to crypto dimensions.": "提升到加密维度",
    "boost to point and leaf gain.": "提升到点数和叶子增益。",
    "Coding": "编码",
    "code experience.": "编码经验。",
    "lines of code per second. (Based on code experience)": "行代码每秒。 （基于编码经验）",
    "Lines of code to make a mod": "制作 模组 的代码行",
    "mods.": "模组。",
    "Reset for code experience": "重置获得编码经验",
    "on reset. (Based on crypto)": "在重置时。（基于加密）",
    "Unlocks something.": "介绍新东西。",
    "Boosts crypto gain based on mods.": "提升加密增益基于模组。",
    "Make Your Mods NFTS!": "让你的模组 NFTS！",
    "seeds per second.": "种子每秒。",
    "seeds, which make trees ^1 stronger": "种子，增强树 ^1",
    "Aarex Running Through Your Veins": "Aarex 穿过你的血管",
    "Beat δ Challenge I.": "击败 δ 挑战 I.",
    "Beta Male Moment": "测试男性时刻",
    "Don't Forget...": "别忘了…",
    "Don't you already have more than a few thousand of these?": "你不是已经有几千个了吗？",
    "Epsilionaire": "Epsilionaire",
    "Enough Antimatter Dimensions References!": "足够的反物质维度参考！",
    "Gain 1000 aarexian energy.": "获得 1000 aarexian 能量。",
    "Gain 1000000 ε.": "获得 1000000 ε.",
    "Gain eee9 points.": "获得 eee9 点数.",
    "Get 1000 β.": "获得 1000 β.",
    "GUIDE HERE (Currently outdated)": "指南在这里（目前已过时）",
    "Get TS level 10.": "获得 TS 10 级。",
    "Get a x11 β dimensions sacrifice multiplier.": "获得 x11 β 维度牺牲乘数。",
    "Get 6 ω.": "获得 6 ω.",
    "Get 65 singularity energy.": "获得65奇点能量。",
    "Omega Layers Reference?": "欧米伽层级参考？",
    "Pi Body Pillow Owner": "Pi 身体枕头所有者",
    "Pi on Drugs": "Pi 药物",
    "Pi Tier 3 Sub": "Pi 层级 3 Sub",
    "Quest Lord": "任务领主",
    "There Will Always Be More Challenges": "总会有更多的挑战",
    "Triple E's": "三倍 E's",
    "Autobuys tree buyables and keep tree upgrades on crypto reset.": "自动购买 树可购买 并在加密重置时保留树升级。",
    "Ugh, Too Much Repetition.": "呃，太多的重复操作。",
    "Black Friday": "黑色星期五",
    "": "",
    "Lowers the price growth of tree buyables.": "降低 树可购买 的价格增长。",
    "Autobuys crypto dimensions and buyables.": "自动购买加密尺寸和可购买物品。",
    "Boosts crypto dimensions production based on when the mod softcap starts.": "根据 模组软上限 开始的时间提高加密维度的生产。",
    "creation mods.": "创作模组。",
    "Creator Realm Lore": "造物主领域传说",
    "Crypto Dimensions go BRR": "加密维度到 BRR",
    "Cryptomator": "加密器",
    "Currently making mods powered by the CREATOR REALM.": "目前正在制作由 造物主领域 提供支持的模组。",
    "Deposit ALL of your mods to the Creator Realm.": "将您所有的模组存入 造物主领域。",
    "Keeps all upgrades on code reset.": "在代码重置时保持所有升级。",
    "loop=true hidden=true autostart=true": "循环=真隐藏=真自动启动=真",
    "No more microtasks!": "没有更多的微任务！",
    "Oh yay a new feature!": "哦耶一个新功能！",
    "On top of the multiverse, lies the mankind.": "在多元宇宙之上，是人类。",
    "Realm Mods": "领域模组",
    "Select the realm you want to deal with.": "选择您要处理的领域。",
    "The humans live yet they can not see": "人活着却看不见",
    "The other realms hiding underneath": "隐藏在下面的其他领域",
    "Toggle Music: Unmute": "切换音乐：取消静音",
    "Unlocks realm mods and gain 6% of crypto per second.": "解锁领域模组并每秒获得 6% 的加密。",
    "Which boost tree and leaf gain by x1.00": "哪一棵树和叶子增加了 x1.00",
    "Yet they can control them with their mind,": "然而他们可以用意念控制他们，",
    "A very liminal place, a horror-filled maze.": "一个非常有限的地方，一个充满恐怖的迷宫。",
    "A very strange world filled with powerful gods": "一个充满强大神灵的非常奇怪的世界",
    "All the stories, made by humans in mankind,": "人类在人类中创造的所有故事，",
    "At the dimensional realm, is where they all reside.": "在维度领域，是他们都居住的地方。",
    "Backrooms Lore": "密室传说",
    "But their vision of paradise, might make it worse.": "但他们对天堂的看法可能会使情况变得更糟。",
    "Currently making mods powered by the BACKROOMS.": "目前正在制作由 BACKROOMS 提供支持的模组。",
    "Currently making mods powered by the DEATH REALM.": "目前正在制作由 DEATH REALM 驱动的模组。",
    "Currently making mods powered by the DIMENSIONAL REALM.": "目前正在制作由 DIMENSIONAL REALM 提供支持的模组。",
    "Currently making mods powered by the HIGHER PLANE.": "目前正在制作由 HIGHER PLANE 驱动的模组。",
    "Currently making mods powered by the VOID.": "目前正在制作由 VOID 提供支持的模组。",
    "Death Realm Lore": "死亡领域传说",
    "Deposit ALL of your mods to the Backrooms.": "将所有模组存入后台。",
    "Deposit ALL of your mods to the Death Realm.": "将所有模组存入死亡领域。",
    "Deposit ALL of your mods to the Dimensional Realm.": "将所有模组存入维度领域。",
    "Deposit ALL of your mods to the Higher Plane.": "将你所有的 mod 存放到更高的平面。",
    "Deposit ALL of your mods to the Void.": "将所有模组存入 Void。",
    "dimensional mods.": "维度模组。",
    "Dimensional Realm Lore": "维度领域知识",
    "divine mods.": "神圣的模组。",
    "fatal mods.": "致命的模组。",
    "Higher Plane Lore": "更高层面的知识",
    "It is very deep, but also very shallow.": "它很深，但也很浅。",
    "It's a boring place, and all signs of life, they lack.": "这是一个无聊的地方，他们缺乏所有生命迹象。",
    "It's like a never ending shadow.": "就像一个永无止境的影子。",
    "liminal mods.": "阈限模组。",
    "Once you noclip in, you are never getting back.": "一旦你进入 noclip，你就再也回不来了。",
    "Realistic, fictional, even ones that don't make sense.": "现实的，虚构的，甚至那些没有意义的。",
    "shadow mods.": "影子模组。",
    "The angels and demons must make their choice.": "天使和恶魔必须做出他们的选择。",
    "The good people can go to heaven, which is great!": "好人能上天堂，真好！",
    "The sinners go to hell, which they will hate.": "罪人会下地狱，这是他们所憎恶的。",
    "There are only two colors, which are grey and black.": "只有两种颜色，灰色和黑色。",
    "They look underneath for chosen ones": "他们在下面寻找被选中的人",
    "They try to spread good through the multiverse": "他们试图通过多元宇宙传播善",
    "Tons of levels, it's like a stack.": "成吨的等级，它就像一个堆栈。",
    "Tons of worlds of many sizes,": "无数大小不一的世界，",
    "Void Lore": "虚空传说",
    "When a being reaches their fate,": "当一个生命到达他们的命运时，",
    "Which makes mod softcap start x1.00 later": "这使得 模组软上限 稍后启动 x1.00",
    "Yet somewhat calm, bringing you in a nostalgic haze.": "又有些沉稳，带你进入怀旧的阴霾。",
    "A long time has passed since the war. The higher plane of existence and the death realms made an alliance.": "战争已经过去很长时间了。 存在的更高层面和死亡领域结盟。",
    "Antimatter Dimensions": "反物质维度",
    "Beginning": "开始",
    "But it was no use. The death realm was all powerful.": "但这没有用。 死界都是强大的。",
    "But one day, the higher plane saw their weapon and wanted to join them.": "但是有一天，更高位面看到了他们的武器，想要加入他们。",
    "Chapter 1": "第1章",
    "Each of the nobles has made great contributions to the backrooms and the void.": "每个贵族都为密室和虚空立下了汗马功劳。",
    "He revolutionized incrementals. He formed a lot of powerful beings known as celestials.": "他彻底改变了增量。 他形成了许多被称为天体的强大生物。",
    "In order to gain the dimensional realm, the backrooms and void used their own energy to create four legendary nobles.": "为了获得次元境界，密室和虚空用自己的能量造就了四位传奇贵族。",
    "Lore": "知识",
    "Meta-Prestige": "元声望",
    "Potential": "潜在的",
    "The backrooms and void have made an alliance, but are still against the higher plane and death realms.": "密室和虚空已经结盟，但仍然反对更高的位面和死亡领域。",
    "The death realm and higher plane cut ties with each other.": "死界与上位面断绝了联系。",
    "The death realm won, and three of the four nobles were exiled.": "死亡领域获胜，四位贵族中的三位被放逐。",
    "The gods from the death realm searched for the incremental nobles.": "死界诸神寻找增量贵族。",
    "The higher plane joined the backrooms and the void, to bring back the exiled nobles and to bring the weapon back.": "更高位面连接密室和虚空，带回被流放的贵族，带回武器。",
    "The knight of upgrades. The ranger of numbers.": "升级骑士。 数字护林员。",
    "The mage of automation. The warrior of infinity.": "自动化法师。 无限战士。",
    "The void and backrooms were unsure, but the death realm was mad at the higher plane.": "虚空和密室不确定，但死亡领域在更高位面是疯狂的。",
    "The warrior of infinity changed his identity. He changed his name to Hevipelle.": "无限战士改变了身份。 他改名为赫维佩尔。",
    "They also extracted power from darkness, and made a POWERFUL WEAPON with most of the energy from the void.": "他们还从黑暗中提取能量，并用大部分来自虚空的能量制造了强大的武器。",
    "They fought in another long war, in order for justice to be made.": "为了伸张正义，他们又进行了一场漫长的战争。",
    "They helped increase the limit of backrooms levels the backrooms could make.": "他们帮助提高了幕后级别的限制。",
    "They were the incremental nobles. They had power of gods and the minds of prodigies.": "他们是增量贵族。 他们拥有神的力量和神童的头脑。",
    "This weapon was so powerful, it could beat THE MULTIVERSAL SPLITTER.": "这把武器太强大了，可以打败 多元宇宙分离器。",
    "To free the other nobles, Hevipelle used his antimatter dimensions to fight back against the death realm.": "为了解放其他贵族，赫维佩尔利用他的反物质维度反击死亡领域。",
    "Willpower": "意志",
    "YOU WILL USE THE WEAPON.": "您将使用该武器。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "i": "i",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Current endgame: ": "当前残局：",
    "trees, which produce ": "树，产生 ",
    "Leaves Booster ": "叶子助推器 ",
    "Points Booster ": "点数助推器 ",
    "Trees Booster ": "树助推器 ",
    "Notation: ": "符号：",
    "Softcap Booster ": "软上限助推器 ",
    "You are making ": "你制造了 ",
    "bytes, which give a ": "字节，它给出了 ",
    "You will gain ": "你将获得 ",
    "You beat ": "你击败了 ",
    "mods, which give a x": "模组，给了一个 x",
    "You are writing  ": "你写了 ",
    "You have  ": "你有 ",
    "You made  ": "你制造了 ",
    "Your code experience gives a x": "你的编码经验给了一个 x",
    "Unlocked Cante (": "解锁 Cante (",
    "Which boost code experience gain by ": "提升编码经验 ",
    "Which boost crypto dimensions gain by ": "提升加密维度 ",
    "Which boost crypto production by ": "将加密生产提高 ",
    "Which boost lines of code gain by ": "提升代码行增益 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " Point Generation.": " 点数生成。",
    " Tree Generation": " 树木生成",
    " Tree Generation.": " 树木生成。",
    " Leaf Generation.": " 树叶生成。",
    " Crypto Dimensions Generation": " 加密维度生成",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^ ([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^\(e([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\(([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Get (.+) singularity blessings$/, '获得 $1 奇点祝福'],
    [/^Get (.+) infinities.$/, '获得 $1 无限。'],
    [/^Get (.+) broken infinities.$/, '获得 $1 突破无限。'],
    [/^Get (.+) replicanti.$/, '获得 $1 复制品。'],
    [/^Get (.+) replicanti mods.$/, '获得 $1 复制品模块。'],
    [/^Get (.+) mods.$/, '获得 $1 模块。'],
    [/^Get (.+) 1st crypto dimensions.$/, '获得 $1 第1加密维度。'],
    [/^Get (.+) singularity theorems.$/, '获得 $1 奇点定理。'],
    [/^Get (.+) shrine power.$/, '获得 $1 神庙力量。'],
    [/^Get (.+) shrine power.$/, '获得 $1 神庙力量。'],
    [/^Get (.+) crypto.$/, '获得 $1 加密。'],
    [/^Get (.+) singularity power$/, '获得 $1 奇点力量'],
    [/^Get (.+) singularity power.$/, '获得 $1 奇点力量。'],
    [/^Get (.+) achievement power.$/, '获得 $1 成就力量。'],
    [/^Get (.+) singularity trees.$/, '获得 $1 奇点树。'],
    [/^Get (.+) infinity power.$/, '获得 $1 无限力量。'],
    [/^Get (.+) infinity points.$/, '获得 $1 无限点数。'],
    [/^Get (.+) code experience.$/, '获得 $1 编码经验。'],
    [/^Get (.+) points.$/, '获得 $1 点数。'],
    [/^After (.+) mods, lines of code gain is divided by (.+) \(Based on mods\)$/, '在 $1 模组后，代码行增益除以 $2（基于模组）'],
    [/^Reach (.+) points.$/, '达到 $1 点数。'],
    [/^Tree softcap starts (.+) later.$/, '树的软上限在 $1 之后开始。'],
    [/^You have ([\d\.]+)e([\d\.,]+)$/, '你有 $1e$2'],
    [/^You have (.+) achievement power.$/, '你有 $1 成就力量。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) points.$/, '你有 $1 点数。'],
    [/^You have (.+) potential.$/, '你有 $1 潜能。'],
    [/^After (.+) trees, leaf gain is divided by (.+) \(Based on trees\)$/, '$1 棵树后，叶子增益除以 $2（基于树）'],
    [/^which makes tree softcap start (.+) later.\n(.+)Cost: (.+) Points$/, '这会使 树 的软上限在 $1 之后开始。\n$2成本：$3 点数'],
    [/^which are shortening tree requirement by (.+).\n(.+)Cost: (.+) Trees$/, '这会使降低 树 的需求 $1。\n$2成本：$3 树'],
    [/^which are boosting your point gain by x(.+).\n(.+)Cost: (.+) Trees$/, '这会使您的 点数 增益提升 x$1。\n$2成本：$3 树'],
    [/^which are boosting your point, leaf and tree gain by x(.+).\n(.+)Cost: (.+) Trees$/, '这会使您的 点数，叶子和树的增益 提升 x$1。\n$2成本：$3 树'],
    [/^which are boosting your point, leaf and tree gain by x(.+).\n(.+)Cost: (.+) Bytes$/, '这会使您的 点数，叶子和树的增益 提升 x$1。\n$2成本：$3 字节'],
    [/^which are boosting your crypto gain by x(.+).\n(.+)Cost: (.+) Bytes$/, '这会使您的 加密 增益提升 x$1。\n$2成本：$3 字节'],
    [/^which boosts all crypto dimension production by x(.+).\n(.+)Cost: (.+) Bytes$/, '这会使您的 全部加密维度生产 提升 x$1。\n$2成本：$3 字节'],
    [/^which are boosts all crypto dimension production x(.+).\n(.+)Cost: (.+) Bytes$/, '这会使您的 全部加密维度生产 提升 x$1。\n$2成本：$3 字节'],
    [/^which are boosting your leaf gain by x(.+).\n(.+)Cost: (.+) Points$/, '这会使您的 叶子 增益提升 x$1。\n$2成本：$3 点数'],
    [/^which gives (.+) bytes per second.\n(.+)Cost: (.+) Crypto\n(.+)$/, '给予 $1 字节每秒。\n$2成本：$3 加密\n$4'],
    [/^which gives (.+) crypto dimension (.+) per second.\n(.+)Cost: (.+) Crypto\n(.+)$/, '给予 $1 加密维度 $2 每秒。\n$3成本：$4 加密\n$5'],
    [/^You are gaining (.+) points per second.$/, '你每秒获得 $1 点数。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) Points a day$/, '$1 点数一天'],
    [/^(.+) Trees a minute$/, '$1 树一分钟'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^You made ([\d\.]+)$/, '你制造了 $1'],
    [/^You have ([\d\.]+)$/, '你有 $1'],
    [/^You have ([\d\.]+)e([\d\.,]+)$/, '你有 $1e$2'],
    [/^You have ([\d\.,]+)$/, '你有 $1'],
    [/^Crypto Dimension ([\d\.]+)$/, '加密维度 $1'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) CR$/, '\+$1 加密重置'],
    [/^\+([\d\.]+) CE$/, '\+$1 编码经验'],
    [/^\+([\d\.,]+) CE$/, '\+$1 编码经验'],
    [/^\+([\d\.]+)e([\d\.,]+) CR$/, '\+$1e$2 加密重置'],
    [/^\+([\d\.]+)e([\d\.,]+) CE$/, '\+$1e$2 编码经验'],
    [/^\+([\d\.]+) CE$/, '\+$1 编码经验'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) Code Experience$/, '成本：$1 编码经验'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) Crypto$/, '成本：$1 加密'],
    [/^Cost: (.+) Points$/, '成本：$1 点数'],
    [/^Cost: (.+) Trees$/, '成本：$1 树'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);